### ISSUE TITLE
Error on note type update

### ISSUE THREAD

**Issue by AnKingMed** [AnKingMed/anking_notes_addon#7]
Ocorreu um erro. Por favor, inicie o Anki enquanto segura a tecla shift, isto vai desabilitar temporariamente as extensões que você instalou.
Se o problema ocorrer somente quando as extensões são habilitadas, use o Ferramentas > Extensões para desabilitar algumas extensões e reinicie o Anki, repetindo até descobrir a extensão que está causando o problema.
Quando você descobrir a extensão que está causando o problema, por favor reporte o problema em site de suporte de extensão.
Informações de Depuração:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-22 09:38:58

Caught exception:
Traceback (most recent call last):
  File "[aqt\taskman.py](http://aqt/taskman.py/)", line 101, in _on_closures_pending
  File "[aqt\taskman.py](http://aqt/taskman.py/)", line 71, in <lambda>
  File "[aqt\taskman.py](http://aqt/taskman.py/)", line 90, in wrapped_done
  File "C:[\Users\leona\AppData\Roaming\Anki2\addons21\952691989\gui\config_window.py](http://users/leona/appdata/roaming/anki2/addons21/952691989/gui/config_window.py/)", line 403, in on_done
    mw.col.models.update_dict(model)  # type: ignore
  File "[anki\models.py](http://anki/models.py/)", line 223, in update_dict
  File "[anki\_backend\generated.py](http://anki/_backend/generated.py/)", line 444, in update_notetype_legacy
  File "[anki\_backend\__init__.py](http://anki/_backend/__init__.py/)", line 131, in _run_command
anki.errors.TemplateError: O modelo do cartão ⁨1⁩ tem um problema.<br>See the preview for more information.

@RisingOrange can you look into this?

**Comment by AnKingMed** [comment]
@RisingOrange I'm heading to bed soon so go ahead and just upload the add-on to ankiweb once you've fixed

I was able to replicate the error:

> Caught exception:
> Traceback (most recent call last):
>   File "aqt.taskman", line 122, in _on_closures_pending
>   File "aqt.taskman", line 71, in <lambda>
>   File "aqt.taskman", line 90, in wrapped_done
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/952691989/gui/config_window.py", line 403, in on_done
>     mw.col.models.update_dict(model)  # type: ignore
>   File "anki.models", line 223, in update_dict
>   File "anki._backend.generated", line 850, in update_notetype_legacy
>   File "anki._backend", line 146, in _run_command
> anki.errors.CardTypeError: Card template ⁨1⁩ in notetype '⁨Physeo-IO one by one⁩' has a problem.<br>See the preview for more information.

**Comment by RisingOrange** [comment]
Solved by d8941d9983b95499299778362bf04c8ae3c79183.
